export const Loader = () => {
  return (
    <div className='w-screen h-screen grid place-items-center'>
      <svg
        xmlns='http://www.w3.org/2000/svg'
        style={{
          background: 'transparent',
          display: 'block',
          shapeRendering: 'auto',
        }}
        width={'100px'}
        height={'100px'}
        viewBox='0 0 100 100'
        preserveAspectRatio='xMidYMid'
      >
        <circle
          cx='50'
          cy='50'
          fill='none'
          className='stroke-[#2B3844] dark:stroke-[#869eb5]'
          strokeWidth='5'
          r='35'
          strokeDasharray='164.93361431346415 56.97787143782138'
        >
          <animateTransform
            attributeName='transform'
            type='rotate'
            repeatCount='indefinite'
            dur='1s'
            values='0 50 50;360 50 50'
            keyTimes='0;1'
          ></animateTransform>
        </circle>
        {/* [ldio] generated by https://loading.io/*/}
      </svg>
    </div>
  );
};
